# Importing and division of data:

In [1]:
import numpy as np
from IPython.display import display,HTML
from numpy import *

np.set_printoptions(suppress=True)

from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))

#### Importing the data

The data was imported using the numpy function ```genfromtxt('file.csv')``` which reads and converts ```.csv``` files into a single ```numpy array``` which will be useful for dividing and saving purposes.

In [2]:
### Importing some useful packages
#This ensures that plots appear in the sheet and not in a new window
%matplotlib inline 

#Pandas is an alternative numerical processing library like numpy: they have differences
#We will use Pandas only to provide a preview of the data once we've read it in
import pandas as pd


data = np.genfromtxt('online_shoppers_intention_selection.csv',delimiter=",")

#Convert the numpy array to a pandas DataFrame
#and display the first 10 rows as html
display(pd.DataFrame(data).head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,21.0,1079.0,4.0,176.0,67.0,2162.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,1.0,11.0,2.0,1.0,0.0
1,6.0,91.0,0.0,0.0,56.0,955.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,4.0,2.0,2.0,1.0,1.0
2,0.0,0.0,0.0,0.0,69.0,1002.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,4.0,2.0,2.0,0.0,0.0
3,8.0,212.0,3.0,124.0,52.0,968.0,0.0,0.0,214.0,0.0,11.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
4,0.0,0.0,0.0,0.0,20.0,301.0,0.0,0.0,0.0,0.0,5.0,3.0,2.0,1.0,3.0,2.0,0.0,0.0
5,3.0,143.0,2.0,29.0,3.0,380.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,4.0,3.0,0.0,0.0,0.0
6,6.0,158.0,1.0,430.0,146.0,5602.0,0.0,0.0,6.0,0.0,11.0,2.0,10.0,7.0,2.0,2.0,0.0,1.0
7,0.0,0.0,0.0,0.0,65.0,1803.0,0.0,0.0,0.0,0.0,5.0,3.0,2.0,6.0,3.0,2.0,0.0,0.0
8,0.0,0.0,0.0,0.0,16.0,381.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,1.0,2.0,2.0,0.0,0.0
9,4.0,75.0,0.0,0.0,10.0,158.0,0.0,0.0,20.0,0.0,10.0,1.0,1.0,3.0,2.0,2.0,1.0,1.0

#### Randomizing the data 

It is important to randomize ones data set before dividing the data into Training, Cross Validtion and Testing data sets. Thus the numpy function ```numpy.random.shuffle(arr)``` was used to shuffle the data by rows while leaving the contents of each row unshifted.

In [3]:
np.random.shuffle(data)
display(pd.DataFrame(data).head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,2.0,162.0,0.0,0.0,0.0,0.0,5.0,2.0,4.0,1.0,4.0,2.0,0.0,0.0
1,2.0,256.0,0.0,0.0,10.0,117.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,7.0,11.0,2.0,1.0,1.0
2,0.0,0.0,0.0,0.0,6.0,31.0,0.0,0.0,0.0,0.0,10.0,2.0,5.0,1.0,1.0,2.0,0.0,0.0
3,8.0,131.0,1.0,4.0,95.0,2107.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,4.0,4.0,2.0,1.0,0.0
4,2.0,8.0,1.0,14.0,14.0,603.0,0.0,0.0,44.0,0.0,3.0,2.0,2.0,1.0,7.0,2.0,0.0,1.0
5,1.0,18.0,0.0,0.0,62.0,1288.0,0.0,0.0,13.0,0.0,11.0,2.0,10.0,1.0,3.0,2.0,0.0,1.0
6,4.0,81.0,0.0,0.0,12.0,223.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
7,16.0,485.0,2.0,19.0,42.0,753.0,0.0,0.0,31.0,0.0,11.0,2.0,2.0,1.0,8.0,2.0,0.0,1.0
8,5.0,1417.0,0.0,0.0,36.0,1051.0,0.0,0.0,0.0,0.0,3.0,2.0,2.0,5.0,2.0,2.0,1.0,0.0
9,3.0,371.0,5.0,106.0,85.0,2128.0,0.0,0.0,43.0,0.0,11.0,1.0,1.0,1.0,2.0,2.0,0.0,1.0

#### Dividing the data

The origional dataset was divided into 3 datasets which are namely, ```Training``` consisting of 60% of the origional data, ```Cross Validation``` consisting of 20% and ```Testing``` consisting of 20% of remaining origional data.

In [4]:
#sets the ratio of training data: validation data: testing data(currently 80:10:10)

perc1= int(0.6*len(data))
perc2= int(0.8*len(data))

train = data[:perc1]
val = data[perc1:perc2]
test = data[perc2:]

In [5]:
print("\nThere is a total of "+(str)(len(data))+ " records in this data set")

#Convert the numpy array to a pandas DataFrame
#and display the first 10 rows as html for each data set

print("\nTraining data: "+(str)(len(train)))
display(pd.DataFrame(train).head(10))
print("\nCV data: "+(str)(len(val)))
display(pd.DataFrame(val).head(10))
print("\nTesting data: "+(str)(len(test)))
display(pd.DataFrame(test).head(10))

There is a total of 3816 records in this data set

Training data: 2289

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,2.0,162.0,0.0,0.0,0.0,0.0,5.0,2.0,4.0,1.0,4.0,2.0,0.0,0.0
1,2.0,256.0,0.0,0.0,10.0,117.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,7.0,11.0,2.0,1.0,1.0
2,0.0,0.0,0.0,0.0,6.0,31.0,0.0,0.0,0.0,0.0,10.0,2.0,5.0,1.0,1.0,2.0,0.0,0.0
3,8.0,131.0,1.0,4.0,95.0,2107.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,4.0,4.0,2.0,1.0,0.0
4,2.0,8.0,1.0,14.0,14.0,603.0,0.0,0.0,44.0,0.0,3.0,2.0,2.0,1.0,7.0,2.0,0.0,1.0
5,1.0,18.0,0.0,0.0,62.0,1288.0,0.0,0.0,13.0,0.0,11.0,2.0,10.0,1.0,3.0,2.0,0.0,1.0
6,4.0,81.0,0.0,0.0,12.0,223.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
7,16.0,485.0,2.0,19.0,42.0,753.0,0.0,0.0,31.0,0.0,11.0,2.0,2.0,1.0,8.0,2.0,0.0,1.0
8,5.0,1417.0,0.0,0.0,36.0,1051.0,0.0,0.0,0.0,0.0,3.0,2.0,2.0,5.0,2.0,2.0,1.0,0.0
9,3.0,371.0,5.0,106.0,85.0,2128.0,0.0,0.0,43.0,0.0,11.0,1.0,1.0,1.0,2.0,2.0,0.0,1.0

CV data: 763

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1.0,112.0,0.0,0.0,8.0,543.0,0.0,0.0,28.0,0.0,10.0,1.0,1.0,6.0,2.0,0.0,1.0,1.0
1,2.0,28.0,0.0,0.0,12.0,224.0,0.0,0.0,44.0,0.0,3.0,3.0,2.0,6.0,2.0,2.0,0.0,1.0
2,2.0,14.0,0.0,0.0,53.0,2016.0,0.0,0.0,8.0,0.0,6.0,2.0,2.0,3.0,3.0,2.0,0.0,1.0
3,1.0,43.0,1.0,0.0,3.0,65.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,1.0,4.0,2.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,6.0,10.0,2.0,0.0,0.0
5,0.0,0.0,0.0,0.0,22.0,573.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,8.0,2.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,12.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
7,3.0,170.0,0.0,0.0,30.0,619.0,0.0,0.0,0.0,0.0,12.0,3.0,2.0,4.0,1.0,2.0,1.0,0.0
8,0.0,0.0,0.0,0.0,7.0,384.0,0.0,0.0,0.0,0.0,5.0,2.0,4.0,1.0,5.0,2.0,0.0,0.0
9,0.0,0.0,0.0,0.0,53.0,1121.0,0.0,0.0,24.0,0.0,7.0,2.0,4.0,9.0,1.0,2.0,0.0,1.0

Testing data: 764

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,8.0,213.0,2.0,45.0,30.0,2054.0,0.0,0.0,21.0,0.0,12.0,1.0,1.0,6.0,2.0,0.0,0.0,1.0
1,3.0,179.0,0.0,0.0,22.0,746.0,0.0,0.0,0.0,0.0,5.0,3.0,3.0,1.0,15.0,2.0,1.0,0.0
2,8.0,410.0,5.0,406.0,24.0,1220.0,0.0,0.0,8.0,0.0,10.0,3.0,2.0,2.0,2.0,2.0,0.0,1.0
3,4.0,157.0,0.0,0.0,20.0,834.0,0.0,0.0,4.0,0.0,12.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
4,3.0,81.0,0.0,0.0,94.0,2487.0,0.0,0.0,0.0,0.0,10.0,2.0,2.0,6.0,2.0,0.0,0.0,0.0
5,8.0,139.0,0.0,0.0,49.0,3346.0,0.0,0.0,12.0,0.0,11.0,2.0,6.0,1.0,2.0,2.0,0.0,0.0
6,1.0,53.0,0.0,0.0,10.0,1331.0,0.0,0.0,49.0,0.0,5.0,2.0,2.0,1.0,4.0,2.0,1.0,1.0
7,11.0,456.0,1.0,13.0,89.0,1904.0,0.0,0.0,0.0,0.0,10.0,1.0,1.0,4.0,3.0,2.0,0.0,0.0
8,2.0,561.0,2.0,31.0,95.0,4817.0,0.0,0.0,50.0,0.0,11.0,1.0,1.0,5.0,2.0,2.0,0.0,1.0
9,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,2.0,1.0,1.0,2.0,0.0,0.0

#### Saving the datasets

The divided datasets were then stored into their respective ```.dat``` files, which was made possible through the use of the function ```savetxt('file.dat')```

In [6]:
#writes the arrays into their respective files
savetxt('data/train.dat', train)
savetxt('data/cv.dat', val)
savetxt('data/test.dat', test)

#### Hint

When loading the datasets make use of the function ```loadtxt('file.dat')``` as illustrated below.

In [7]:
c = loadtxt('data/train.dat')
display(pd.DataFrame(c).head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,2.0,162.0,0.0,0.0,0.0,0.0,5.0,2.0,4.0,1.0,4.0,2.0,0.0,0.0
1,2.0,256.0,0.0,0.0,10.0,117.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,7.0,11.0,2.0,1.0,1.0
2,0.0,0.0,0.0,0.0,6.0,31.0,0.0,0.0,0.0,0.0,10.0,2.0,5.0,1.0,1.0,2.0,0.0,0.0
3,8.0,131.0,1.0,4.0,95.0,2107.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,4.0,4.0,2.0,1.0,0.0
4,2.0,8.0,1.0,14.0,14.0,603.0,0.0,0.0,44.0,0.0,3.0,2.0,2.0,1.0,7.0,2.0,0.0,1.0
5,1.0,18.0,0.0,0.0,62.0,1288.0,0.0,0.0,13.0,0.0,11.0,2.0,10.0,1.0,3.0,2.0,0.0,1.0
6,4.0,81.0,0.0,0.0,12.0,223.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
7,16.0,485.0,2.0,19.0,42.0,753.0,0.0,0.0,31.0,0.0,11.0,2.0,2.0,1.0,8.0,2.0,0.0,1.0
8,5.0,1417.0,0.0,0.0,36.0,1051.0,0.0,0.0,0.0,0.0,3.0,2.0,2.0,5.0,2.0,2.0,1.0,0.0
9,3.0,371.0,5.0,106.0,85.0,2128.0,0.0,0.0,43.0,0.0,11.0,1.0,1.0,1.0,2.0,2.0,0.0,1.0